<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IelBexio.Domain\IelBexio.Domain.csproj" />
    <ProjectReference Include="..\..\src\IelBexio.Application\IelBexio.Application.csproj" />
    <ProjectReference Include="..\..\src\IelBexio.Infrastructure\IelBexio.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\IelBexio.Web\IelBexio.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>
</Project>
