<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Azure.AI.OpenAI" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\IelBexio.Domain\IelBexio.Domain.csproj" />
    <ProjectReference Include="..\IelBexio.Application\IelBexio.Application.csproj" />
  </ItemGroup>
</Project>
